image: eclipse-temurin:21-jdk

variables:
  ORG_GRADLE_PROJECT_ci: 'true'

# Verification (tests and code analysis) is unnecessary on 'develop' &
# 'main', because only verified MRs can be merged into those branches.
.verification:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: never
    - if: $CI_COMMIT_BRANCH == "develop"
      when: never
    - when: on_success

stages:
  - build
  - check
  - docker_image
  - deployment

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - when: always

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  rules:
    - when: on_success
  variables:
    IMAGE_NAME: eu.gcr.io/veo-projekt/veo-reporting
    GOOGLE_APPLICATION_CREDENTIALS: $GCR_ACCESS_TOKEN
  script:
    - env
    - |-
      ADDITIONAL_TAGS="pipeline-id-${CI_PIPELINE_ID}"
      if [ -n "$CI_COMMIT_TAG" ]; then export ADDITIONAL_TAGS="$ADDITIONAL_TAGS,$CI_COMMIT_TAG";
        if [ "$CI_COMMIT_REF_NAME" = "main" ]; then export ADDITIONAL_TAGS="$ADDITIONAL_TAGS,latest"; fi;
      fi;
      if [ "$CI_COMMIT_REF_NAME" = "develop" ]; then export ADDITIONAL_TAGS="$ADDITIONAL_TAGS,develop"; fi;
    - ./gradlew -i -PciBuildNumer=$CI_PIPELINE_ID -PciJobName=$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME -PciCommitId=$CI_COMMIT_SHA jib -Djib.console=plain -Djib.to.image="$IMAGE_NAME:gitlab-git-${CI_COMMIT_SHA}" -Djib.to.tags="$ADDITIONAL_TAGS"
  interruptible: true
  cache:
    - key: gradle
      paths:
        - .gradle
    - key: $CI_PROJECT_PATH
      paths:
        - build
      policy: push

test:
  stage: check
  rules:
    - !reference [.verification, rules]
  script: ./gradlew -i test
  interruptible: true
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
  cache:
    - key: gradle
      paths:
        - .gradle
    - key: $CI_PROJECT_PATH
      paths:
        - build
      policy: pull

check:
  stage: check
  rules:
    - !reference [.verification, rules]
  interruptible: true
  script:
    - ./gradlew -i check -x test
  cache:
    - key: gradle
      paths:
        - .gradle
    - key: $CI_PROJECT_PATH
      paths:
        - build
      policy: pull

trigger_deployment:
  stage: deployment
  only:
    - develop
    - main
  trigger:
    project: veo/verinice-veo-deployment
