#
# Copyright (c) 2021 Jochen Kemnade.
#
# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#

veo:
  reporting:
    veo_url: https://veo.develop.verinice.com
    http_proxy_host: null
    http_proxy_port: 3128
    use_filebased_template_loading: false
    use_template_cache: true

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true