#
# verinice.veo reporting
# Copyright (C) 2021  Jochen Kemnade
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
veo:
  reporting:
    veo_url: https://api.verinice.example/veo
    http_proxy_host: null
    http_proxy_port: 3128
    use_filebased_template_loading: false
    use_template_cache: true
    cors:
      # A comma-separated list of allowed CORS origin-patterns.
      # Example: https://*.domain1.com, https://*.domain1.com:[8080,8081], https://*.domain1.com:[*]
      origins: https://veo-web.verinice.example
      # A comma-separated-list of additional headers to allow in CORS requests
      # Note: The 'Authorization' and 'Content-Type' headers are always allowed.
      # Example: X-Ample, X-Custom-Header
      headers:
management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
server:
  compression:
    enabled: true
spring:
  jndi:
    ignore: true
  threads:
    virtual:
      enabled: true